### ISSUE TITLE
Send message

### ISSUE THREAD

**Issue by alreadylostmyself** [sudoio/vk-chat-bot#2]
Can you add possible send message to user without any event was handled?
Just `bot.send()` or something like that

**Comment by sudoio** [comment]
Hello. Thanks for using my library :)
I don't think of adding `bot.send()` yet.
However, you can send a message without handler like this:
```js
// Get the API instance from bot (after bot initialization)
var api = bot.behavior.api

// (User ID, message, attachments)
api.send(1, 'Test Message', 'photo6492_45624077')
```
The `API#send()` documentation can be found [here](https://github.com/sudoio/vk-chat-bot/wiki/API#send).

**Comment by alreadylostmyself** [comment]
Thx for helpful information, you must add this in wiki, maybe someone more will want to use it :)

**Comment by sudoio** [comment]
Added to [`API`](https://github.com/sudoio/vk-chat-bot/wiki/API) wiki :)
